name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installer nødvendige pakker hvis du har en requirements.txt

    - name: Create Lambda ZIP file
      run: |
        zip -r lambda_code.zip *

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Upload Lambda ZIP to S3
      uses: aws-actions/aws-s3-sync-action@v1
      with:
        bucket: fraktals3
        source: lambda_code.zip
        destination: "lambda_code.zip"

    - name: Deploy Lambda Function
      run: |
        aws lambda update-function-code \
          --function-name codeTestLambda \
          --s3-bucket fraktals3 \
          --s3-key lambda_code.zip
