name: Lambda Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create ZIP file
      run: |
        zip -r ${{ secrets.LAMBDA_ZIP_NAME }} .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Upload to S3
      run: |
        aws s3 cp ${{ secrets.LAMBDA_ZIP_NAME }} s3://${{ secrets.S3_BUCKET_NAME }}/${{ secrets.LAMBDA_ZIP_NAME }}

    - name: Deploy Lambda
      run: |
        aws lambda update-function-code --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --s3-key ${{ secrets.LAMBDA_ZIP_NAME }}
